# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ejaazApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker`

  # Pods for ejaazApp

  target 'ejaazAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ejaazApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ejaazApp-tvOS

  target 'ejaazApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
